// PHASE-15: Smart Journal Entries System - Automated Journal Entry DTOs
// This file contains DTOs for automated journal entries

import { JournalEntryResponseDto } from '../journal-entries/journal-entry.dto';

export interface AutomatedJournalEntryDto {
  id: string;
  journalEntryId: string;
  // إضافة علاقة عكسية اختيارية للقيد الذكي
  journalEntry?: JournalEntryResponseDto;
  sourceType: string;
  sourceId: string;
  templateId?: string;
  isAutoGenerated: boolean;
  createdAt: Date;
}

export interface CreateAutomatedJournalEntryDto {
  sourceType: string;
  sourceId: string;
  templateId?: string;
  journalEntryData: CreateJournalEntryFromTemplateDto;
}

export interface CreateJournalEntryFromTemplateDto {
  templateId: string;
  sourceData: Record<string, any>;
  entryDate?: Date;
  description?: string;
  fiscalYearId?: string;
  fiscalPeriodId?: string;
}

export interface CreateJournalEntryFromOperationDto {
  operationType: string;
  sourceType: string;
  sourceId: string;
  sourceData: Record<string, any>;
  entryDate?: Date;
  description?: string;
  fiscalYearId?: string;
  fiscalPeriodId?: string;
}

export interface ValidateJournalEntryDto {
  lines: ValidateJournalEntryLineDto[];
  entryDate: Date;
  fiscalYearId?: string;
}

export interface ValidateJournalEntryLineDto {
  accountId: string;
  debit: number;
  credit: number;
}

export interface JournalEntryValidationResultDto {
  isValid: boolean;
  errors: string[];
  warnings: string[];
  totalDebit: number;
  totalCredit: number;
  isBalanced: boolean;
}
